### ISSUE TITLE
the code copied didn't work

### ISSUE THREAD

**Issue by jackeryjam** [dplewis/parse-server-mysql-adapter#20]
Hello!
  I copy the code to run, but found "MySQL is not a constractor", I change "const MySQL = require('parse-server-mysql-adapter').MySQL" into "const MySQL = require('parse-server-mysql-adapter')", then the code run continue. 
  After that, I face another problem that request me to add fileAdaptor once I add database adaptor, I add "var FSFilesAdapter = require('@parse/fs-files-adapter');", and this was solved.
  Finally, what problem I met is "TypeError: this.adapter.updateSchemaWithIndexes is not a function", so I had no way but turn to you.
  Can you run the demo code nowadays and how can I solve this.
  Thank you very much!

**Comment by dplewis** [comment]
Hello,

Thanks for using this adapter. Unfortunately, I haven't touched this adapter since Parse-Server 2.5.0. I've been busy adding new features to get 2.7.0 out the door. This adapter has yet to support indexes, aggregates, distinct queries, etc.

For the error you received you can try to add this line to the adapter.

```
updateSchemaWithIndexes() {
  return Promise.resolve();
}
```

I'll try to get the adapter up-to-date ASAP.

In the meantime if you want to play around with the adapter, I made a repo for testing.

https://github.com/dplewis/parse-server-mysql-test

**Comment by jackeryjam** [comment]
Thanks for your answer, I use parse-server@2.5.0 to deploy successfully.

**Comment by dplewis** [comment]
No Problem, I'll work on improving the adapter this weekend.
